### PR TITLE
Added Materialize NavBar, with MatchList, Chat, and Profile icons

### PR DESCRIPTION
**Pull request by trm313**
Basic navbar included with icon navigation for MatchList, Chat, and Profile. I made it green for now -> anyone have suggestions on color scheme? 

I was considering having the navbar items collapse when viewed on mobile, but I'm not sure that's ideal (at least for options such as the Chat), so I haven't included at this point.

Routes not created, so the buttons don't link anywhere. I can create those pretty soon, just need to do some more research into them - didn't want that to hold Philippe up with this one

### CODE REVIEW

**Comment by Neoflash1979** [comment]
For the color scheme, we could take a look at https://material.io/color/ to help us decide.

**Comment by trm313** [comment]
Thanks for the comments Philippe - I'll remove the spec file

Regarding the navbar width - I'm used to top navs extending to the ends of the screen and not residing in the container (any examples of the alternative? I checked a few sites but didn't see any that didn't). 

However, I could implement some containment on the items within the navbar, so that they stay more centered on larger screens.

And just for clarity, the nav-bar is still sitting on top of a container div that will keep the actual site contents contained

**Comment by Neoflash1979** [comment]
@trm313 "I could implement some containment on the items within the navbar, so that they stay more centered on larger screens."

That is what I'm suggesting. Of course, the bar itself would extend to end of the screen, just the content would be contained. With materializecss it would be very simple to do it. You simply have to do wrap the content of your div.nav-wrapper in a div.container, like this:
```
<nav class="teal accent-4">
  <div class="container">
    <div class="nav-wrapper">
       ....
    </div>
  </div>
</nav>
```
Give it a try and let me know what you think.

**Comment by trm313** [comment]
Yep I understand what you mean now - I read it too quickly and interpreted it wrong. I'll touch it up when I'm back home

**Pull request merged**
